Класс ExampleUser разделен на 2 сущности, добавлена типизация
it-for-free/SimpleMVC-example pull request #21
Opened 2023-07-28 18:26 UTC by NewDeveloper111

Класс ExampleUser разделен на 2 сущности, выборочно добавлена типизация.

2023-07-29 11:27 UTC, vedro-compota requested changes

2023-07-29 11:27 UTC, vedro-compota commented on README.md
> +* Добавить возможность редактирования роли пользователя, проверить стили на странице редактирования.
дописать "в админке"

2023-07-29 11:27 UTC, vedro-compota commented on application/models/AuthUser.php
> +	$siteAuthData = $User->checkAuth($login);
Предлагаю переименовать этот метод тут и классе-источнике на getAuthData() - чтобы он отражал смысл

2023-07-29 11:51 UTC, vedro-compota requested changes

2023-07-29 11:51 UTC, vedro-compota commented on application/models/UserModel.php
> +    public function getRole($login) {
Добавить типизацию возвращаемого значения

2023-07-29 11:51 UTC, vedro-compota commented on application/models/UserModel.php
> +    public function checkAuth($login) {
вот тут как раз переименовать, предлагаю как-то типизировать ответ - null если не нашли и может ассоциативный массив, если нашли, чтобы клиенсткий код "понимал" на что рассчитывать

2023-07-29 15:59 UTC, NewDeveloper111 commented on application/models/UserModel.php
> +    public function checkAuth($login) {
Исправлено.

2023-07-29 15:59 UTC, NewDeveloper111 commented on application/models/UserModel.php
> +    public function getRole($login) {
Исправлено.

2023-07-29 15:59 UTC, NewDeveloper111 commented on application/models/AuthUser.php
> +	$siteAuthData = $User->checkAuth($login);
Исправлено.

2023-07-29 16:00 UTC, NewDeveloper111 commented on README.md
> +* Добавить возможность редактирования роли пользователя, проверить стили на странице редактирования.
Исправлено.

2023-07-29 21:04 UTC, vedro-compota requested changes

2023-07-29 21:04 UTC, vedro-compota commented on README.md
> +* Добавить в админке возможность редактирования роли пользователя, проверить стили на странице редактирования.
Разбить на два пункта - стили отдельно (можно раньше поставить), правку роли - отдельно. и там и там приписать что это про админку

2023-07-30 10:32 UTC, NewDeveloper111 commented on README.md
> +* Добавить в админке возможность редактирования роли пользователя, проверить стили на странице редактирования.
Исправлено.

2023-07-30 11:17 UTC, merged