Добавлен контроллер и вид для отображения ошибок
it-for-free/SimpleMVC-example pull request #6
Opened 2020-07-19 16:08 UTC by toyrik

В файл web/index.php добавлен перехват всплывающих ощибок и передача их
в ErrorHandler для обработки
В файле web/autoload.php добавлен перехват ошибки подключения файла

2020-08-01 19:42 UTC, vedro-compota requested changes
требуются правки, добавлены комментарии к разным фрагментам

2020-08-01 19:42 UTC, vedro-compota commented on web/autoload.php
>  <?php
откатить правки, тут ничего не надо

2020-08-01 19:42 UTC, vedro-compota commented on application/views/error.php
> +use ItForFree\SimpleMVC\DebugPrinter;
предлагаю откатить отдачу заголовка вообще

2020-08-15 18:56 UTC, vedro-compota requested changes
просьба ещё поправить

2020-08-15 18:56 UTC, vedro-compota commented on web/autoload.php
> +    require_once $fileName;
или пояснение оптимизации или просьба отменить изменения

2020-08-15 18:56 UTC, vedro-compota commented on web/index.php
откатить все в этом файле

2020-08-16 06:39 UTC, toyrik commented
Поправил

2020-08-19 16:10 UTC, vedro-compota requested changes

2020-08-19 16:10 UTC, vedro-compota commented on web/autoload.php
> -
в этом файле полностью отменяем изменения

2020-08-19 16:10 UTC, vedro-compota commented on web/index.php
аналогично откатываем изменения

2020-08-19 17:52 UTC, vedro-compota requested changes
в папке docs/  в корне просьба создать файл ExeptionsHandling.md и описать там функционал, счанала преамбула, а потом пояснения с цитатами кода с указанием путей к файлам.

2020-08-21 06:10 UTC, toyrik commented
То есть что то [подобное](https://github.com/it-for-free/SimpleMVC-example/pull/6/commits/51800f760d00911eea93bb8f5330a36663d0adda), я правильно понимаю?

2020-08-29 17:15 UTC, merged